name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Gaphor dependencies
        run: >
          dnf install -y gcc git pipx graphviz pkg-config python-launcher upx
          mutter dbus-x11 gtksourceview5 libadwaita
          cairo-gobject-devel

      - name: Install library
        run: uv sync --locked --all-extras --dev

      - name: Setup node
        uses: actions/setup-node@v6

      - name: install node packages
        run: npm install

      - name: run tests
        run: uv run pytest
